name: lint
on:
  - push
  - pull_request

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: install markdown-cli
        run: npm install -g markdownlint-cli
      - name: lint
        run: npx markdownlint '**/*.md'